@startuml
[*] --> On_Ground
state On_Ground {
    note right
        Actions:
        - Add passengers
        - Add crew
        - Plan route
    end note
}

state In_Air {
    note right
        Actions:
        - Serve meals
        - Serve drinks
        - Ensure safety
    end note
}

On_Ground --> In_Air : take_off()
In_Air --> On_Ground : land()
@enduml